### ISSUE TITLE
Lecture 7 link broken

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/61a-editor#16]
FYI, https://code.cs61a.org/07.py gives a 404, perhaps because it times out (or maybe because of the unusual imports).

**Comment by rahularya50** [comment]
Sorry, the cache didn't clear for some reason. The link works now, at least for me.

**Comment by rahularya50** [comment]
What happens is after each commit to master `course_deploy` sends a POST request to code.cs61a.org to refresh its cache, but there's some sort of race condition where the POST request is sometimes handled before cs61a.org itself is updated.

So immediately after commiting a new lecture.py file, sometimes code.cs61a.org will be out of date. I might end up just removing the cache entirely, and accessing the registry every time a shortlink is accessed, if I can't fix this issue some other way.

**Comment by papajohn** [comment]
Thanks!
